### ISSUE TITLE
I have installation issue on pcap. 

### ISSUE THREAD

**Issue by sanket-mindstix** [mranney/node_pcap#105]
SOLINK_MODULE(target) Release/obj.target/pcap_binding.node
/usr/bin/ld: cannot find -lpcap
collect2: ld returned 1 exit status
make: *** [Release/obj.target/pcap_binding.node] Error 1
make: Leaving directory `/home/sanket/git_Test_pcap/node_pcap/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/opt/node/lib/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:797:12)
gyp ERR! System Linux 3.5.0-49-generic
gyp ERR! command "node" "/opt/node/bin/node-gyp" "configure" "build"
gyp ERR! cwd /home/sanket/git_Test_pcap/node_pcap
gyp ERR! node -v v0.10.26
gyp ERR! node-gyp -v v0.13.1
gyp ERR! not ok

**Comment by jmaxxz** [comment]
Can you retest this with the latest version?

**Comment by jmaxxz** [comment]
Closed as original author failed to respond. Reopen if it can be reproduced.
