### ISSUE TITLE
Server responses multiple cookies,but pcap only shows one.

### ISSUE THREAD

**Issue by fanchangyong** [mranney/node_pcap#106]
I use http_trace --headers to capture the http traffic.And I use 
 curl -i -d 'email=MYEMAIL&password=MYPASSWORD' www.zhihu.com/login
to issue a login operation on a website,which will response some cookies from server.
below is what curl prints the cookies:
Set-Cookie: q_c0="MmM4ZjIxZGQ5OGMxMTI3YzM2OWRmODdlZjM5NTQzM2J8Nk5zeHMxaVExQmZGaXY4Rw==|1405187412|60833e0abcbe71b3596468fc4f1265e801f164c5"; Domain=zhihu.com; httponly; Path=/
Set-Cookie: c_c=; Domain=zhihu.com; expires=Fri, 12 Jul 2013 17:50:12 GMT; Path=/
Set-Cookie: r_i=; Domain=zhihu.com; expires=Fri, 12 Jul 2013 17:50:12 GMT; Path=/
Set-Cookie: sinaid=; Domain=zhihu.com; expires=Fri, 12 Jul 2013 17:50:12 GMT; Path=/
Set-Cookie: qqconn_access_token=; Domain=zhihu.com; expires=Fri, 12 Jul 2013 17:50:12 GMT; Path=/
Set-Cookie: qqconn_openid=; Domain=zhihu.com; expires=Fri, 12 Jul 2013 17:50:12 GMT; Path=/
Set-Cookie: l_c=; Domain=zhihu.com; expires=Fri, 12 Jul 2013 17:50:12 GMT; Path=/
Set-Cookie: sina_access_token=; Domain=zhihu.com; expires=Fri, 12 Jul 2013 17:50:12 GMT; Path=/
Set-Cookie: r_e=; Domain=zhihu.com; expires=Fri, 12 Jul 2013 17:50:12 GMT; Path=/

but in http_trace,I can only see the last cookie in the headers.

**Comment by jmaxxz** [comment]
Try https://github.com/mranney/http_trace 

http_trace is not its own project and not part of node_pcap. (though still makes use of it)
