### ISSUE TITLE
packets delayed by one

### ISSUE THREAD

**Issue by chrisdew** [mranney/node_pcap#110]
There's some odd behaviour - the pcap_seesion.on('packet', ...) seems to work as a FIFO with a capacity of one.  i.e. the nth event is emitted when the n+1th packet is captured.

Is there a way to remove this one packet "buffer" and have 'packet' events emitted immediately?

**Comment by mranney** [comment]
I can't reproduce this. Can you make a simple example program where this happens?

On my Mac, I just did:

    sudo examples/simple_capture en0 icmp

And then in another window, I did:

    ping -c 1 8.8.8.8

And I saw both the ICMP echo and ICMP reply come back.
