### ISSUE TITLE
Setup travis CI build which runs tests and hints code

### ISSUE THREAD

**Issue by jmaxxz** [mranney/node_pcap#133]
Having a travis ci build really helps in determining the state of pull requests.

  -  [x] Setup travis
   -  [x] Run hinter on travis
   -  [x] Run unit tests on travis
  -  [x] Setup coveralls

**Comment by jmaxxz** [comment]
@mranney Any chance you will be able to log in to Travis CI and enable the build on this repo?

**Comment by jmaxxz** [comment]
@mranney when you get around to it could you also enable coveralls? https://coveralls.io/repos/new after you do that I will turn on code coverage in the CI build.

**Comment by mranney** [comment]
I enabled both. I've never used either service, so I'm not familiar with the workflow. Is there a way to kick off a build manually?

**Comment by jmaxxz** [comment]
@mranney it happens automatically, but yes you can kick one manually as well. If you are online this evening I can give you a tour.
