### ISSUE TITLE
radiopacket.decode does not work in current version on npm

### ISSUE THREAD

**Issue by AlexanderSelzer** [mranney/node_pcap#134]
There's this error when decoding 80211 probe packets (`wlan type mgt subtype probe-req` filter):

```
/home/as/git/umdtc/node_modules/pcap/decode/pcap_packet.js:45
        this.payload = new RadioPacket.decode(buf, 0);
                       ^
TypeError: undefined is not a function
``` 

When using the current version on GitHub it works, so I assume the npm package would just need to be updated.

**Comment by jmaxxz** [comment]
This is fixed in master. Next time the npm package is reved the fix will be available.
