### ISSUE TITLE
Readme is out of date and needs to be updated

### ISSUE THREAD

**Issue by aferre** [mranney/node_pcap#136]
Hi,

I updated my dependencies with the master branch (previously I used the dependency provided by npm). Can you please update the wiki and example? http_trace example doesn't seem to work any more: I have no packlet printed

Thank you

**Comment by jmaxxz** [comment]
Do you get a stack trace?

**Comment by aferre** [comment]
No stack trace at all. There is just nothing printed (bodies or headers). With the same arguments, I do have the bodies and headers

**Comment by jmaxxz** [comment]
This issue probably belongs on the [http trace repository](https://github.com/mranney/http_trace).

I have never used this example before and was able to get it to work with the provided usage. Here is what I did:

```
git clone git@github.com:mranney/http_trace.git
cd http_trace
sudo ./http_trace --headers
```

However the when I tried to get the bodies with it did not work so well:
```bash
sudo ./http_trace --bodies
```

I hope this helps, but I would suggest opening an issue on the http_trace project.

**Comment by jmaxxz** [comment]
Point taken though, the readme is out of date on this project.

**Comment by aferre** [comment]
I red the code on http_trace repo. 

Seems that it's not based on pcap anymore, but the one in the examples directory still is.

**Comment by jmaxxz** [comment]
@aferre it absolutely is. Here are 2 lines from the code that indicate it does use node_pcap.
[node_pcap being required in](https://github.com/mranney/http_trace/blob/master/http_trace#L11)
[node_pcap declared as a dependency](https://github.com/mranney/http_trace/blob/master/package.json#L11)

**Comment by jmaxxz** [comment]
Pull #147  will close this issue by removing examples from this repo and updating readme.

**Comment by jmaxxz** [comment]
http_trace is not completely stand alone.
