### ISSUE TITLE
packet injection.

### ISSUE THREAD

**Issue by fridaystreet** [mranney/node_pcap#140]
Hi,

I wonder if anyone is able to provide me with some assistance in understanding how to formulate a packet for injection please? I have seen the inject.js example and that works I can detect it monitoring with tcpdump, but I am trying to create a beacon frame and it just never seems to send anything.

What are the requirements for what needs to go in a packet to use inject? I've tried creating a beacon by capturing one in wireshark and copying that in to a buffer, but I'm thinking the full packet in wireshark maybe has an amount of extra info that is added by the driver and maybe that's where I'm going wrong. Does anyone now what parts of the frame need to be passed to inject a beacon?

Many thanks in advance
Paul

**Comment by fridaystreet** [comment]
Probably should have left an example of the packet I have

//Radio tap header
0x00,  										//header revision
0x00, 										//header pad
0x19, 0x00, 									//header length
0x6f, 0x08, 0x00, 0x00, 							//Present Flags
0xe2, 0xd4, 0x7c, 0xe4, 0x00, 0x00, 0x00, 0x00, 		//mac timestamp
0x12, 										//flags
0x0c, 										//data rate
0x3c, 0x14, 									//channel
0x40, 0x01, 									//channel type
0xe2, 										//SSI Signal
0xa5, 										//SSI Noise
0x00, 										//Antenna

//IEEE 802.11 Beacon Frame
0x80, 0x00,									//Type/Subtype Beacon Frame control Field
0x00, 0x00, 									//Duration: 0 microseconds 
0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 						//Receiver Address
0x60, 0xa4, 0x4c, 0x6a, 0x00, 0x84,					//Transmitter Address
0x60, 0xa4, 0x4c, 0x6a, 0x00, 0x84,					//BSSID
0xa0, 0x89,									//Fragment number - Sequence number

//IEEE 802.11 Management Frame
//Fixed parameters
0x3c, 0x00, 0x9a, 0xa8, 0x3a, 0x00, 0x00, 0x00, 		//Timestamp
0x64, 0x00, 									//Beacon Interval
0x11, 0x00,									//Capabilities

//Tagged Parameters
//SSID
0x00,										//Tag type
0x06,										//Tag length 
0x4b, 0x42, 0x57, 0x4c, 0x41, 0x4e, 					//SSID

//supported rates
0x01, 										//Tag Type
0x08, 										//tag length
0x8c, 0x12, 0x98, 0x24, 0xb0, 0x48, 0x60, 0x6c, 		//supported rates (1 each)

//Remaining tags
0x05, 0x04, 0x00, 0x01, 0x00, 0x00, 0x30, 0x14, 0x01, 0x00, 0x00, 0x0f, 0xac, 0x04, 0x01, 0x00, 0x00, 0x0f, 0xac, 0x04, 0x01, 0x00, 0x00, 0x0f, 0xac, 0x02, 0x0c, 0x00, 0x2d, 0x1a, 0xad, 0x08, 0x17, 0xff, 0xff, 0xff, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x3d, 0x16, 0x24, 0x08, 0x04, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x7f, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x40, 0xbf, 0x0c, 0xb2, 0x40, 0x82, 0x0f, 0xea, 0xff, 0x00, 0x00, 0xea, 0xff, 0x00, 0x00, 0xc0, 0x05, 0x00, 0x24, 0x00, 0x00, 0x00, 0xc3, 0x02, 0x00, 0x02, 0xdd, 0x09, 0x00, 0x10, 0x18, 0x02, 0x03, 0x00, 0x1c, 0x00, 0x00, 0xdd, 0x18, 0x00, 0x50, 0xf2, 0x02, 0x01, 0x01, 0x80, 0x00, 0x03, 0xa4, 0x00, 0x00, 0x27, 0xa4, 0x00, 0x00, 0x42, 0x43, 0x5e, 0x00, 0x62, 0x32, 0x2f, 0x00, 

0xe4, 0x57, 0x5a, 0xed							//Frame check sequence number

**Comment by jmaxxz** [comment]
What driver? What Os?

**Comment by fridaystreet** [comment]
It's on a raspberry pi with an rt2870 loading rt2x00lib_request_firmware
version 0.29

Rt chipset 5390 rev 0502
Rf chipset 5370

**Comment by fridaystreet** [comment]
Pi is running wheezy

**Comment by jmaxxz** [comment]
Look at http://svn.aircrack-ng.org/trunk/src/aireplay-ng.c the source used for [aireplay's injection attack test](http://www.aircrack-ng.org/doku.php?id=injection_test)

By my read you need to send the following:
```
"00"+MacAddress+"40000000FFFFFFFFFFFFCCCCCCCCCCCCFFFFFFFFFFFF0000"+ssidTag+"010402040B1632080C1218243048606C"
```

Explained:
```
40000000FFFFFFFFFFFFCCCCCCCCCCCCFFFFFFFFFFFF0000 == Probe Frame Header
010402040B16 == Rates tag (tag id == 1, length==4)
32080C1218243048606C == Extended rates (tag id == 50, length == 8)
```

**Comment by fridaystreet** [comment]
@jmaxxz Thanks for the info. Yeah I wanted to send a beacon, but even if I could send a probe response that would be a good start. I've tried your suggestion, but still nothing showing up :-(

Apologies I'm not really skilled up in C, I'm looking through the aircrack stuff, but it doesn't really make a lot of sense to me. 

hahaha na just doing some research and testing at the moment to see what is possible.

cheers
Paul

**Comment by jmaxxz** [comment]
Try running the aireplay injection test just to make sure your current set up supports injection. Assuming it does I will do a bit more research for you.

```
aireplay-ng -9 wlan0 
```

**Comment by fridaystreet** [comment]
Thanks for the suggestion, yeah that's the path I ended up going down. It's working ok with aireplay so I'm pretty sure it's just how I have the bytes setup in the buffer I'm sending to inject.
