### ISSUE TITLE
Decode radiotap header correctly

### ISSUE THREAD

**Issue by jmaxxz** [mranney/node_pcap#143]
Right now the flags bit mask is not being parse. This results in misreading the header for any flag value other than `2f480000`.

Issue was found by @fridaystreet and reported on pull #129.

**Comment by jmaxxz** [comment]
http://www.radiotap.org/ is the specification I will be using to decode this information.

**Comment by jmaxxz** [comment]
@fridaystreet please verify fix.

Note: strength got renamed to signalStrength.

**Comment by fridaystreet** [comment]
@jmaxxz awesome! working great now thanks
