### ISSUE TITLE
TCPTracker does not raise start or end events.

### ISSUE THREAD

**Issue by jpacora** [mranney/node_pcap#156]
Hello, im using the code of the example:
```javascript
var pcap = require('pcap'),
    tcp_tracker = new pcap.TCPTracker(),
    pcap_session = pcap.createSession('en1', "ip proto \\tcp");

tcp_tracker.on('start', function (session) {
    console.log("Start of TCP session between " + session.src_name + " and " + session.dst_name);
});

tcp_tracker.on('end', function (session) {
    console.log("End of TCP session between " + session.src_name + " and " + session.dst_name);
});

pcap_session.on('packet', function (raw_packet) {
	console.log('packet')
    var packet = pcap.decode.packet(raw_packet);
    tcp_tracker.track_packet(packet);
});
```
And the events "start" and "stop" doesn't work, i has added the console.log('packet') to see if pcap is getting some packets, and yes, its working.

**Comment by jmaxxz** [comment]
I have not done much work with tcp_tracker, but try this and see if it meets your needs:
```javascript
tcp_tracker.on('session', function (session) {
    console.log("Start of TCP session between " + session.src_name + " and " + session.dst_name);
});
```

I am still looking into what is going on with the start and end events.

**Comment by jmaxxz** [comment]
Confirmed bug still exists in master.

**Comment by jpacora** [comment]
Please fix that :(

**Comment by jmaxxz** [comment]
@jpacora right now this is pretty low on my to-do list. There are right now I am focused on getting this library tested. tcp_tracker is near the top of the stack, and therefore will be one of the last files I get around to. Though I will take very brief look at it today to see if it is an obvious error, but don't get your hopes up.


If you need something sooner you can fix it and open a pull request which I will field ASAP.

**Comment by jmaxxz** [comment]
The new way of doing what you want appears to be the following. (assuming you are working off of master)

```javascript
var pcap = require('./pcap'),
    tcp_tracker = new pcap.TCPTracker(),
    pcap_session = pcap.createSession('en0', "ip proto \\tcp");

tcp_tracker.on('session', function (session) {
  console.log("Start of session between " + session.src_name + " and " + session.dst_name);
  session.on('end', function (session) {
      console.log("End of TCP session between " + session.src_name + " and " + session.dst_name);
  });
});

pcap_session.on('packet', function (raw_packet) {
    var packet = pcap.decode.packet(raw_packet);
    tcp_tracker.track_packet(packet);
});
```
