### ISSUE TITLE
Has node_pcap's packet API changed?

### ISSUE THREAD

**Issue by brannondorsey** [mranney/node_pcap#157]
It seems to me that once a `raw_packet` has been decoded with `pcap.decode.packet()` the stack does not match that of the documentation and examples. For instance this code in the README throws a `TypeError: Cannot read property 'ip' of undefined` as `link` is not a property of packet:

```
packet.link.ip.tcp.dport
```

It also seems that any example that uses `pcap.link.x...` is broken (dns.js and network_grep.js most notably) because of this.

**Comment by jmaxxz** [comment]
What version are you using? Currently master has significantly diverged from the last release on npm. There is a lot more changes coming before the next drop.

**Comment by brannondorsey** [comment]
I'm using the current npm version (2.0.1). Should I instead be using the GitHub master branch? Both appear not to support the stack style data structure documented in the README relied on by the examples (unless I am mistaken).

**Comment by jmaxxz** [comment]
Yes, this style is going away. Honestly for right now inspecting the returned values is going to be your best option for figuring out the api.

If you choose to use master expect a lot of changes. By the time we release 3.0 we should have a large quantity of tests which will make the usage more discover-able.

For specific questions about the new code hit us up on [![Join the chat at https://gitter.im/mranney/node_pcap](https://badges.gitter.im/Join%20Chat.svg)](https://gitter.im/mranney/node_pcap?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge)
