### ISSUE TITLE
Static dependency on libpcap

### ISSUE THREAD

**Issue by kriskowal** [mranney/node_pcap#159]
It would greatly simplify using node_pcap in the wild if it were to bundle libpcap such that it does not depend on libpcap-dev to be installed as a system dependency on Linux. Are there moral objections to that approach?

**Comment by jmaxxz** [comment]
IMO this would not be a good change. This creates a disparity between node_pcap an other pcap based tools on the user's box.  Furthermore as I understand your idea this would make it even hard to support windows.

**Comment by mranney** [comment]
I don't think we should do this, because it'll break on non-Linux platforms. 

Are you trying to address the mysterious build system error if this isn't installed, or are you trying to avoid having to install an OS package on a production machine that your config management system is going to wipe out the next time it runs?

**Comment by kriskowal** [comment]
The build error is in fact mysterious, and that is an issue worth investigating.

I’m not terribly worried about my config management system wiping out libpcap-dev next time it runs. I only need it to exist when I npm install my project.

I am pursuing alternative approaches in parallel. On one hand, I trying to get libpcap-dev included in the configuration management system’s manifest of packages just-available in production. Barring that, I am going to pursue getting this tool that uses node_pcap into a .deb and getting that package added to the configuration management system’s manifest.

The issue I hope to address with this suggestion is that both of these alternative approaches are heavy and slow, much more heavy and slow than `npm install -g my_pcap_tool` on production machines when and where we need it.

**Comment by jmaxxz** [comment]
> On one hand, I am trying to get libpcap-dev included in the configuration management system’s manifest of packages just-available in production.

This is what you should do. If you want to build against a static version of node_pcap you are going to have to fork this project and do that on your own fork. Then use `npm install --from-git git@github.com:kriskowal/node_pcap` to take a dependency on your version.

**Comment by brannondorsey** [comment]
For those who might be interested, I've done just what @jmaxxz recommended. [My fork](https://github.com/brannondorsey/node_pcap) bundles OSX and linux (64bit) static builds of libpcap v1.5.3 and uses them when compiling node_pcap w/ node-gyp. Might be helpful for folks looking to do this in the future.

**Comment by jmaxxz** [comment]
@brannondorsey ty for reporting back. Glad to hear that worked for you.
