### ISSUE TITLE
decode: ideas for representing protocol name in the decoded packet

### ISSUE THREAD

**Issue by skepticfx** [mranney/node_pcap#161]
I was going through the new node_pcap changes and I can understand that the API for decoding is based on using the `instanceof` operator. This actually broke the old test cases I used to have internally and am having some hard time refactoring them, because of the way I wrote them. Thats not a problem now. 

After talking with @mranney , he explained how V8 works and suggested an option, just quoting it here for reference: 

```
"The problem is that V8 wants to have a stable object shape. 
It wants the property names to be the same for every object it creates with that constructor.
But I know what you mean about trying to figure out what kind of packet you actually have. 
Would it help if we had something like payload.name which always had the name of the packet type?"
```

Also a problem that I see right now is that, all the constructors of the Packet types needs to be exposed to the program using node_pcap somehow. For instance, whenever we use something like, `packet.payload instanceof IPv4`, the IPv4 and other protocols that we might want to compare are not directly exposed. I know we could use `constructor.name` to access the same property using a string, but nothing is as elegant as ip.tcp.ssl or ip.udp.dns.

I've started this thread to discuss more ideas on how to make this better, if there are any. Right now, setting `payload.name='packet_type'` looks like the better one to me.

**Comment by jmaxxz** [comment]
Great write up!

From a usage side I do agree with you, there is a fairly large advantage to using the `payload.payload.payload` scheme on the decoding side as it allows us to rely more heavily on polymorphism, which in turn will make it much easier to extend for more protocols.


From a consumption side/discoverability it at first seems `packet.ip.tcp.http` is easier to use. However this view of the world IMO quickly falls apart when we consider the layered nature of the network stack. Low parts of the stack vary independent of higher protocols. So while `ip.tcp` works on my machine your machine may need to do `802-11.lcp.ip.tcp`.

So far every use of this library I have seen is looking for the results of a very specific decoder. (i.e. looking for tcp packets). I have been playing with the idea of using a form of eventing where you specify the protocols you are interested in. This would allow for an optimization where one can precompute a decoder set and avoid running decoders which can never generate the desired events. This would benefit greatly from payload.payload.payload scheme the new version uses and maybe solve the usage problem.

Thoughts?

**Comment by jmaxxz** [comment]
As for the constructor exposure, this should not be a problem. As a show in the test suite it could be useful to have access to the constructors of the decoders as they work independent of libpcap.

**Comment by mranney** [comment]
How about if we had a single object that exposed all known decoders? Like maybe we export them all from require("pcap") somehow?

**Comment by skepticfx** [comment]
Sounds like a good one @jmaxxz. The use case is mostly on L3 or above most of the times. And that is where you would see more people extending and contributing decoders.

Probably, once we start writing the new API docs, an example of how to write a decoder for an application layer would be useful. I can do that once its time. We just need to fine tune the API for someone to easily contribute decoders.

**Comment by skepticfx** [comment]
@mranney Yeah! Something like, 

`` `
var pcap = require('pcap');
var Protocols = pcap.Protocols; // An object with all the Protocol Constructors
```

and a developer could
```
if(packet.payload instanceof Protocols.IPv4) {

}
```

Or maybe something better?

**Comment by skepticfx** [comment]
Also, I feel its better if we load all the protocol decoders dynamically without hardcoding them in to `index.js` under `decode`.

Perhaps, we could load all the files under the `decode` and expose with the file name as the Protocol name by requiring them.

In index.js, we could:
```
fs.readdirSync(__dirname).forEach(function(x){
    if(x === 'index.js') return;
    exports[x.replace('.js', '')] = require('./'+x);
  });
```

**Comment by jmaxxz** [comment]
@skepticfx I am with you up to the dynamic loading bit.  I can't say I am opposed to the idea, I am just not on board yet. Can you find examples of other well respect node modules doing similar things?

I have a bit more work ahead getting tests around the decoders (and refactoring). After this I will be free to work/think about other concerns and may come around to your view fairly quickly.

**Comment by skepticfx** [comment]
@jmaxxz Good point there. I thought, we can keep these protocol decoders consistent and modular. Nothing much other than that.

**Comment by jmaxxz** [comment]
I have added this to the milestone 3 goals as I feel a great api for consuming packets should be one of our priorities for the next major/breaking change.

**Comment by vigneshshanmugam** [comment]
We can try to do this either by commonJs way or AMD through exports and imports.

**Comment by jmaxxz** [comment]
I added the first draft of the new api today. It is very far from final, but I believe it gives a good idea where I would like to see this go.  The following is an example usage:

```javascript
var eventEmitter = new events.EventEmitter()
eventEmitter.on("tcp", function(tcp){
    console.log(tcp.toString());
});
pcap_session.on('packet', function (raw_packet) {
    var packet = pcap.decode(raw_packet, eventEmitter);
});
```

With this approach we should be able to avoid exposing the constructors entirely as one just says what they are interested in and they get only that part of the packet.

Keeping mind this is a very early version does anyone have any thoughts?

**Comment by skepticfx** [comment]
Looks very elegant to me :+1: 

Nice work there.
