### ISSUE TITLE
error running on MIPS architecture

### ISSUE THREAD

**Issue by fridaystreet** [mranney/node_pcap#165]
Hi,

I'm hoping this is something you may be able to assist with or at least give some direction, but I appreciate it's probably not a priority for you. Although that said getting this module running on the mips platform would probably be quite advantageous and open the door to a lot of applications of it's use.

Anyway, I've managed to get the module at least compiled along with it's dependancies in openwrt on the ar7xxxx architecture using an awesome node cross platform compiler script by Nelson Neves here https://github.com/nneves/openwrt_mips_ar9331_nodejs. It took a bit of tweaking to get it to finally compile properly and actually run on the mips device, but got there in the end. If I can get past the error below and get it fully working I'll happily document the process.

When I try and run any scripts that try to open a pcap session I just get the following error. This was produced just using the dns.js in the example files, if you need a reference as to what js is being used.

warning: eth0: no IPv4 address assigned - this may not actually work
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
Aborted

I've googled the std::bad_alloc and it appears to be an issue in regards to running out of memory. Some suggestions in reply to other code snippets (which may not apply here) are that using &var references is creating temporary memory allocation which are lost when the function ends or something. I noticed in pcap_session.cc that there are a few of these, so I'm not sure if that means anything. I can run node on the device ok without errors. I've tried running a while loop to see if I can kill it in can it is actually running out of memory, but it's runs fine. and running top shows it still having around 30mb ram free even while running node. It only has 64mb which I realise is a small amount, but tcpdump runs fine on it and is able to utilise libpcap. So I'm hoping this will be able to as well.

Apologies I have no knowledge of C++, but if someone is able to assist me it would be greatly appreciated. I'm actually happy to pay for someone's time if required as I would really like to get this working for a project we are working on.

Cheers
Paul

**Comment by mranney** [comment]
We use some larger buffers by default, which might not be appropriate on your more modest hardware. Try lowering them and see if that helps.

**Comment by fridaystreet** [comment]
Hi Matt,

Thanks for the heads up, that done the trick :-)

Cheers
Paul
