### ISSUE TITLE
Question about loading packet captures from wireshark.

### ISSUE THREAD

**Issue by LiamKarlMitchell** [mranney/node_pcap#176]
Can this library or another open the pcap or pcapng  files to work with the data inside?

Basically I am wanting to make a script to load a capture and replay one side of the conversation :D

**Comment by LiamKarlMitchell** [comment]
Ah answered my own question,
https://github.com/kunklejr/node-pcap-parser

**Comment by jmaxxz** [comment]
FYI This library can also load packets from wireshark.

**Comment by LiamKarlMitchell** [comment]
A how? would be nice :)

I know it was mentioned somewhere the documentation was getting reworked and the code being improved. I understand that can be an arduous task.

For anyone who sees this in the future:
```
Pcap.createOfflineSession(filepath, filter)
```

**Comment by jmaxxz** [comment]
@LiamKarlMitchell ty, for adding that!
