### ISSUE TITLE
npm install pcap failed (node-gyp rebuild fails on system)

### ISSUE THREAD

**Issue by royleekiat** [mranney/node_pcap#177]
![image](https://cloud.githubusercontent.com/assets/9070504/9500539/a382e090-4c58-11e5-9fa8-9a0968a69d72.png)

On Windows 8.1 machine with NodeJS 0.12.7 installed (latest) 

I'm quite new to NodeJS, is there any workaround for this?

Thanks!

**Comment by hortinstein** [comment]
it looks like you need to install python on that system and set your env variables correctly.

https://docs.python.org/2/using/windows.html

**Comment by royleekiat** [comment]
@hortinstein It worked, Thanks a lot! (Can't believe I missed that)

**Comment by Chris2011** [comment]
I have the same issue, but I have python installed (v2.7.10), I filed a bug here: https://github.com/mranney/node_pcap/issues/190

**Comment by rezen** [comment]
@Chris2011 did you try `npm config set python C:\Python27\python.exe`?

**Comment by Chris2011** [comment]
Yes, I think that this was the problem, this ticket was very great and helped me: https://github.com/nodejs/node-gyp/issues/629
