### ISSUE TITLE
this.session.open_live - syntax error

### ISSUE THREAD

**Issue by fuunnx** [mranney/node_pcap#207]
Hi, I have an error on a fresh installation of node_pcap:

It works fine when the filter arg is an empty string:
```javascript
var pcapSession = pcap.createSession('en0', '')
```

But when I set it to a specific filter, e.g:
```javascript
var pcapSession = pcap.createSession('en0', 'tcp.port eq 55082')
```

I get this error:
```javascript
/path/to/project/node_modules/pcap/pcap.js:49
        this.link_type = this.session.open_live(this.device_name, this.filter, this.buffer_size, this.outfile, packet_ready, this.is_monitor);
                                      ^

Error: syntax error
    at Error (native)
    at new PcapSession (/path/to/project/node_modules/pcap/pcap.js:49:39)
    at Object.exports.createSession (/path/to/project/node_modules/pcap/pcap.js:123:12)
    at Object.<anonymous> (/path/to/project/project/index.js:5:24)
```

## My configuration:
- Node: v5.1.0
- mac OS X yosemite

## Further informations:
I installed `pcap` via npm from the github repo because I got a error on node-gyp rebuild when installing via npm repo.

**Comment by skepticfx** [comment]
@fuunnx I think your syntax for the filter is wrong. You should rather try something like,
``var pcapSession = pcap.createSession('en0', 'tcp port 55082')``

instead of ``tcp.port eq 55082``

You can read more about pcap filters here: http://linux.die.net/man/7/pcap-filter

**Comment by fuunnx** [comment]
Indeed, it fixed the issue 😃 

My bad, I used the Wireshark syntax. Thank you !

Maybe should we have more explicit error messages for this?

**Comment by skepticfx** [comment]
Glad its resolved. Yeah! Having explicit error messages would be great. 

Send in a pull request if you got some time to work on that :)
