### ISSUE TITLE
TCP_tracker session_stats error.

### ISSUE THREAD

**Issue by abkqz** [mranney/node_pcap#23]
When trying to use session_stats for non-http packets, 

1109     if (session.http.request) {
1110         stats.http_request = session.http.request;
1111     }

fails since http is undefined here. I've fixed it to something like 

1109     if (session.http && session.http.request) {
1110         stats.http_request = session.http.request;
1111     }

and it worked after that.

**Comment by mranney** [comment]
Fixed.
