### ISSUE TITLE
decode wifi "monitoring mode"

### ISSUE THREAD

**Issue by mranney** [mranney/node_pcap#3]
Understand the different types of 802.11 frames and do something sensible with them.

**Comment by fridaystreet** [comment]
Hi,

Does this issue have anything to do with the fact that it isn't reading the wireless frames correctly. All properties of the wireless frame are returned as blank or 0? Do you know if this should be working?

{ link_type: 'LINKTYPE_IEEE802_11_RADIO',
  pcap_header: { tv_sec: 1423979941, tv_usec: 547732, caplen: 187, len: 187 },
  payload: 
   { headerRevision: 0,
     headerPad: 0,
     headerLength: 4608,
     ieee802_11Frame: 
      { frameControl: 0,
        type: 0,
        subType: 0,
        flags: 0,
        duration: 0,
        bssid: { addr: [ 0, 0, 0, 0, 0, 0 ] },
        shost: { addr: [ 0, 0, 0, 0, 0, 0 ] },
        dhost: { addr: [ 0, 0, 0, 0, 0, 0 ] },
        fragSeq: 0,
        strength: -10 } } }


Cheers
Paul

**Comment by jmaxxz** [comment]
@fridaystreet is correct, something is seriously wrong with the ieee802_11Frame packet. I was have been trying to implement decoders for some additional ieee802_11 management packets, but am running into problems with some of the upstream decoders.

While attempting to decode a pcap containing a single beacon packet the value of raw_packet[offset] varies significantly between attempts. This leads me to believe that by the time RadioFrame.decode is run offset has already been incremented past the useful part of the buffer, and is now pointing to uninitialized garbage.

**Comment by jmaxxz** [comment]
found the issue, it is in the header length parsing. The length puts the decoder way past the end of the packet. Need to look at slicing the buffer to detect overruns earlier. (e.g. don't let decode functions index past the end of the packet)

**Comment by jmaxxz** [comment]
#128 fixes header decoding.

**Comment by jmaxxz** [comment]
At this point something sensible is being done, so closing this issue. Reopen if you feel more is needed before it is 'sensible'.

**Comment by fridaystreet** [comment]
@jmaxxz It's working great thanks for your help
