### ISSUE TITLE
install error on v0.6.2

### ISSUE THREAD

**Issue by frede** [mranney/node_pcap#43]
$ node -v
v0.6.2
$ node-waf configure build
Checking for program g++ or c++          : /usr/bin/g++ 
Checking for program cpp                 : /usr/bin/cpp 
Checking for program ar                  : /usr/bin/ar 
Checking for program ranlib              : /usr/bin/ranlib 
Checking for g++                         : ok  
Checking for node path                   : not found 
Checking for node prefix                 : ok /usr 
Checking for library pcap                : yes 
'configure' finished successfully (0.105s)
Waf: Entering directory `/home/hans/node_modules/node_pcap/build'
[1/2] cxx: pcap_binding.cc -> build/Release/pcap_binding_1.o
../pcap_binding.cc:2:25: fatal error: node_events.h: Datei oder Verzeichnis nicht gefunden
compilation terminated.
Waf: Leaving directory `/home/hans/node_modules/node_pcap/build'
Build failed:  -> task failed (err #1): 
	{task: cxx pcap_binding.cc -> pcap_binding_1.o}

npm looks the same. node_path? path? (what should be the content of?) libpcap is installed under /usr/include/pcap.

any ideas?
thanks a lot

**Comment by mranney** [comment]
Closing long ago fixed issue.
