### ISSUE TITLE
examples not working in v0.8.11 due to IOWatcher?

### ISSUE THREAD

**Issue by hb9cwp** [mranney/node_pcap#55]
When trying to run pcap examples in v0.8.11, they print 
 "WARNING: don't use IOWatcher, it'll be removed in v0.9"
and immediately return without capturing any packets.

Apparently, IOWatcher is broken since 0.7.9
 https://github.com/joyent/node/issues/4136

According to Ben Noordhuis, IOWatcher is deprecated and will be removed with no replacement. 
 https://groups.google.com/forum/?fromgroups=#!topic/nodejs/uIzIrSrmW7k

Description How to migrate from ev_io_* to uv_poll_* for IO polling
 https://github.com/joyent/node/wiki/How-to-migrate-from-ev_io_*-to-uv_poll_*-for-IO-polling

Has anyone worked on this already? Thanks.

**Comment by mranney** [comment]
This is fixed with SocketWatcher.
