### ISSUE TITLE
How would I save and reload existing captures?

### ISSUE THREAD

**Issue by LiamKarlMitchell** [mranney/node_pcap#97]
Can pcap do this?
I want to have a way to record captured sessions and analyse them later.

**Comment by jmaxxz** [comment]
see issue #138 maybe reach out to @ben-rowe and collaborate on a solution to save raw_packet data from node.

**Comment by jmaxxz** [comment]
Like @mranney said in #138 if you come up with a good solution please share it with us. It would be a great example project for us to link to!
